### ISSUE TITLE
I need to see images in normal MRI image 

### ISSUE THREAD

**Issue by saikiranvanam** [pietz/brats-segmentation#2]
Hi, when i run your code i'm get output images as you shown in sample. but i need those images in normal MRI Image view. Can you please tell me how can I make get images as i uploaded below?
![Capture](https://user-images.githubusercontent.com/48523583/54509296-1db35400-496f-11e9-8031-ba9ab082913c.JPG)
![Capture1](https://user-images.githubusercontent.com/48523583/54509297-1db35400-496f-11e9-878c-dfe268b8d26c.JPG)

**Comment by pietz** [comment]
Are you referring to the perspective or the applied mask using different
colors?

saikiranvanam <notifications@github.com> schrieb am Mo., 18. März 2019,
06:45:

**Comment by saikiranvanam** [comment]
Thank you for acknowledgment. In one of the image is it shows white and gray matter from grayscale MRI Image.

Mainly I need in that perspective, it would be more helpful for me if you make to show gray, white and tumor in different mask colors.
Especially I need in that perspective.

**Comment by pietz** [comment]
Regarding the perspective: If your segmentation happens on a transversal
axis you need to collect the 2D slices, make them 3D and view the tensor
from a sagittal perspective. That's just some reshaping in numpy regarding
the axes.

Regarding the color: If you have more than 3 channels you need to map every
single one to a custom color or shade of gray in order to visualize it.
Loop over the segmentation channels and add pixels of a specific
brightness/color to a new 3D tensor.

saikiranvanam <notifications@github.com> schrieb am Mo., 18. März 2019,
07:40:

**Comment by sraghu7** [comment]
Hi, when I run the code im getting the output as shown in your example. how to get fine tuned outputs(without any blurr). please help me......
![index](https://user-images.githubusercontent.com/48912416/54916692-216f4980-4f20-11e9-9f0a-a55757c998bb.png)

**Comment by pietz** [comment]
@sraghu7 `The create_data()` function has a resize parameter that is set to 32x32x32. Increasing these values to multiples of 32 should work without needing to adjust the rest of the code. Also, please take some time to understand the code before asking questions. This one should have been obvious for you.

**Comment by sraghu7** [comment]
@pietz  Thanks sir for your suggestions.
